django_practice/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo_list.urls", namespace="todo_list")),
]

todo_list/urls.py
from django.urls import path

from .views import (
    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagListView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    toggle_task_state,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path(
        "<int:pk>/change-state/",
        toggle_task_state,
        name="toggle-task-state",
    ),
    path("<int:pk>/detail", TaskDetailView.as_view(), name="task-detail"),
    path("<create/", TaskCreateView.as_view(), name="task-create"),
    path("<int:pk>/update", TaskUpdateView.as_view(), name="task-update"),
    path("<int:pk>/delete", TaskDeleteView.as_view(), name="task-delete"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/<int:pk>/", TagDetailView.as_view(), name="tag-detail"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "todo_list"

todo_list/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField()
    is_completed = models.BooleanField()
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ("-created_at",)

    def __str__(self) -> str:
        return self.content

todo_list/forms.py
from django import forms

from todo_list.models import Task, Tag


class TaskSearchForm(forms.Form):
    content = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by content"}),
    )
    not_completed = forms.BooleanField(required=False)


class TagSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}),
    )


class TaskForm(forms.ModelForm):
    deadline = forms.SplitDateTimeField()
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(), widget=forms.CheckboxSelectMultiple, required=False
    )

    class Meta:
        model = Task
        fields = "__all__"

todo_list/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from todo_list.forms import TaskSearchForm, TagSearchForm, TaskForm
from todo_list.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    queryset = Task.objects.prefetch_related("tags")
    template_name = "todo_list/task_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)

        content = self.request.GET.get("content", "")
        not_completed = self.request.GET.get("not_completed", "")

        context["search_form"] = TaskSearchForm(
            initial={"content": content, "not_completed": not_completed}
        )
        return context

    def get_queryset(self):
        form = TaskSearchForm(self.request.GET)

        if form.is_valid():
            if form.cleaned_data["not_completed"]:
                return self.queryset.filter(
                    name__icontains=form.cleaned_data["content"], is_completed=False
                )
            return self.queryset.filter(content__icontains=form.cleaned_data["content"])


class TaskDetailView(generic.DetailView):
    model = Task


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo_list:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm

    def get_success_url(self):
        return reverse_lazy("todo_list:task-detail", args=[self.object.pk])


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo_list:task-list")


class TagListView(generic.ListView):
    model = Tag
    queryset = Tag.objects.all()
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TagListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = TagSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        form = TagSearchForm(self.request.GET)

        if form.is_valid():
            if form.cleaned_data["name"]:
                return self.queryset.filter(name__icontains=form.cleaned_data["name"])
            return self.queryset


class TagDetailView(generic.DetailView):
    model = Tag
    fields = "__all__"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TagDetailView, self).get_context_data(**kwargs)

        tag = Tag.objects.get(id=self.kwargs["pk"])
        tasks = Task.objects.filter(tags__id=tag.id)
        context["tasks"] = tasks
        return context


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo_list:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"

    def get_success_url(self):
        return reverse_lazy("todo_list:tag-detail", args=[self.object.pk])


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo_list:tag-list")


def toggle_task_state(request, pk):
    task = Task.objects.get(id=pk)
    if not task.is_completed:
        task.is_completed = True
    else:
        task.is_completed = False
    task.save()
    return HttpResponseRedirect(reverse_lazy("todo_list:task-detail", args=[pk]))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Task Manager</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body style="opacity: 0.95">

<div style="opacity: 1" class="container-fluid content">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link text-white bg-dark">prev</a>
      </li>
    {% endif %}
    <li class="page-item disabled">
      <span class="page-link text-white bg-secondary">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link text-white bg-dark">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/search_form.html
{% load crispy_forms_filters %}
<form action="" method="get" class="form-inline" >
  {{ search_form|crispy }}
  <span></span><input style="margin-left: 10px" type="submit" value="Search" class="btn btn-secondary ">
</form>

templates/includes/sidebar.html
 <a class="list-group-item list-group-item-action list-group-item-dark" href="{% url 'todo_list:task-list' %}">Home</a>
 <a class="list-group-item list-group-item-action list-group-item-secondary" href="{% url 'todo_list:tag-list' %}">Tags</a>

templates/todo_list/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete {{ tag.name }} tag?</h1>
  <i>All information related to this tag will be lost!</i>
  <form action="" method="post">
    {% csrf_token %}
    <hr>
    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'todo_list:tag-detail' pk=tag.id %}" class = "btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/todo_list/tag_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Tag: {{ tag.name }}
    <a href="{% url 'todo_list:tag-delete' pk=tag.id %}" class="btn btn-danger link-to-page float-right ml-1">
      Delete
    </a>

    <a href="{% url 'todo_list:tag-update' pk=tag.id %}" class="btn btn-secondary link-to-page float-right">
      Update
    </a>
  </h1>
  <hr>
  <ul>
    {% if tasks %}
    <h3>
      Tasks related to this tag:
    </h3>
      <br>
    {% for task in tasks %}
      <a href="{% url 'todo_list:task-detail' pk=task.id %}" class="list-group-item list-group-item-action list-group-item-secondary">{{ task.content }}</a>
    {% endfor %}
    {% else %}
    <h3> There are no tasks related to this tag.</h3>
    {% endif %}
  </ul>
{% endblock %}

templates/todo_list/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
    {% if object %}
      <a href="{% url 'todo_list:tag-detail' pk=tag.id %}" class="btn btn-secondary">Cancel</a>
    {% else %}
      <a href="{% url 'todo_list:tag-list' %}" class="btn btn-secondary">Cancel</a>
    {% endif %}
  </form>
{% endblock %}

templates/todo_list/tag_list.html
{% extends "base.html" %}

{% block content %}
    <h1>
    Tags list
    <span class="float-right">
      <a href="{% url 'todo_list:tag-create' %}" class="btn btn-primary link-to-page">
       <i class="bi bi-plus-lg"></i> Create
      </a>
    </span>
  </h1>
  {% block search_form %}
  {% include "includes/search_form.html" %}
  {% endblock %}
  <hr>

  {% if tag_list %}
    <ul class="list-group">
      {% for tag in tag_list %}
          <a href="{% url "todo_list:tag-detail" pk=tag.id %} "
             class="list-group-item list-group-item-action list-group-item-secondary">
            {{ tag.name }} <br>
            Tasks related to this tag: {{ tag.tasks.count }}</a>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no cars in taxi</p>
  {% endif %}

{% endblock %}

templates/todo_list/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <i>All information related to the task will be lost!</i>
  <form action="" method="post">
    {% csrf_token %}
    <hr>
    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'todo_list:task-detail' pk=task.id %}" class = "btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/todo_list/task_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Task: {{ task.content }}
    <a href="{% url 'todo_list:task-delete' pk=task.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'todo_list:task-update' pk=task.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
    {% if task.is_completed %}
    <a href="{% url 'todo_list:toggle-task-state' pk=task.id %}" class="btn btn-danger link-to-page">
      Mark as not completed
    </a>
    {% elif not task.is_completed %}
      <a href="{% url 'todo_list:toggle-task-state' pk=task.id %}" class="btn btn-success link-to-page">
        Mark as completed
      </a>
    {% endif %}
  </h1>
  <hr>
  {% if task.is_completed %}
    <p>This task is completed!</p>
  {% else %}
    <p>This task is not done yet!</p>
  {% endif %}
  <hr>
  {% if task.tags %}
    <h4>Related tags for this task:</h4>
    {% for tag in task.tags.all %}
      <a href="{% url 'todo_list:tag-detail' pk=task.id %}" class="list-group-item list-group-item-action list-group-item-secondary">{{ tag.name }}</a>
    {% endfor %}
  {% else%}
    <h4>There are no related tags for this task.</h4>
  {% endif %}
{% endblock %}

templates/todo_list/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
    {% if object %}
      <a href="{% url 'todo_list:task-detail' pk=task.id %}" class="btn btn-secondary">Cancel</a>
    {% else %}
      <a href="{% url 'todo_list:task-list' %}" class="btn btn-secondary">Cancel</a>
    {% endif %}
  </form>
{% endblock %}

templates/todo_list/task_list.html
{% extends "base.html" %}


{% block content %}
      <h1>
      Task List
      <span class="float-right">
        <a href="{% url 'todo_list:task-create' %}" class="btn btn-primary link-to-page">
          <i class="bi bi-plus-lg"></i> Create
        </a>
      </span>
    </h1>

  {% block search_form %}
  {% include "includes/search_form.html" %}
  {% endblock %}
  <br>
  {% if task_list %}
    <table class="table table-hover">
      <tr>
        <th>ID</th>
        <th>Content</th>
        <th>Created at</th>
        <th>Deadline</th>
        <th>Tags</th>
        <th></th>
      </tr>
      {% for task in task_list %}
          <tr class="table-secondary" onclick="window.location='{% url "todo_list:task-detail" pk=task.id%}'">
            <td>{{ task.id }}</td>
            <td>{{ task.content }}</td>
            <td>{{ task.created_at | date:"d M Y" }}</td>
            <td>{{ task.deadline | date:"d M Y" }}</td>
            <td>{% for tag in task.tags.all %} (<i>{{ tag.name }}</i>){% endfor %}</td>
            <td>{% if task.is_completed %} <span class="btn btn-success disabled float-right"><i class="bi bi-check"></i> Task is done</span>{% endif %}</td>
            </td>
          </tr>
      {% endfor %}

  </table>
  {% else %}
    <p>There are no tasks to do.</p>
  {% endif %}
{% endblock %}